import { Listing } from './types';

export const MOCK_LISTINGS: Listing[] = [
  {
    id: '1',
    slug: '17-acres-washington-county-oh',
    title: '17 Acres in Washington County, OH - Reed Road',
    state: 'OH',
    county: 'Washington',
    nearestTown: 'Marietta',
    acreage: 17,
    price: 99340,
    isNew: true,
    shortDescription: 'Prime 17-acre parcel on Moss Run Road in Washington County. Excellent hunting property with mixed hardwoods and easy access. Perfect for recreational land or future home site.',
    overview: 'This exceptional 17-acre tract on Moss Run Road offers an ideal opportunity for hunters and outdoor enthusiasts in Washington County, Ohio. The property features mature hardwoods providing excellent cover for deer and turkey, with natural topography creating ideal bedding areas and travel corridors.',
    photos: [],
    roadFrontage: '',
    utilities: 'Electric available at road',
    parcelId: 'HOC-2024-001',
    youtubeUrl: '',
    mapEmbedHtml: 'https://id.land/ranching/maps/76e6e7c7facd3792a865cfa6c2d2891f/share',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    slug: '160-acres-washington-county-oh',
    title: '160 Acres in Washington County, OH - State Route 26',
    state: 'OH',
    county: 'Washington',
    nearestTown: 'Marietta',
    acreage: 160,
    price: 649900,
    isNew: true,
    shortDescription: 'Impressive 160-acre tract with State Route 26 frontage in Washington County. Excellent timber value, abundant wildlife, and multiple use potential. A rare large acreage opportunity in southeast Ohio.',
    overview: 'This substantial 160-acre property along State Route 26 represents a premier land opportunity in Washington County, Ohio. With significant road frontage on a major state route, the property offers exceptional accessibility while maintaining the privacy and seclusion that serious land buyers demand.\n\nThe acreage features mature timber stands with strong commercial value, rolling terrain ideal for wildlife management, and the size necessary for serious hunting operations. At 160 acres, the property provides sufficient scale for establishing food plots, creating sanctuary areas, and implementing comprehensive habitat improvements. The land\'s natural features support robust populations of whitetail deer, turkey, and small game.\n\nBeyond recreational use, this property offers flexibility for timber investment, potential development opportunities given its SR 26 frontage, or simply holding as a legacy asset. Properties of this size with paved road access are increasingly rare in Washington County, making this a noteworthy opportunity for investors, serious hunters, or those seeking a significant land holding in southeast Ohio.\n\nThe combination of size, location, and natural resources makes this 160-acre tract a standout offering in the current market.',
    photos: [],
    roadFrontage: '',
    utilities: 'Electric available at road',
    parcelId: '',
    youtubeUrl: '',
    mapEmbedHtml: '',
    createdAt: new Date('2023-11-10'),
  },
  {
    id: '3',
    slug: '25-acres-wood-county-wv',
    title: '25 Acres in Wood County, WV - Happy Hollow Road',
    state: 'WV',
    county: 'Wood',
    nearestTown: 'Parkersburg',
    acreage: 25,
    price: 250000,
    isNew: true,
    shortDescription: 'Beautiful 25-acre woodland parcel on Happy Hollow Road in Wood County, West Virginia. Peaceful setting with excellent hunting potential and recreational opportunities in the heart of WV hill country.',
    overview: 'Discover the natural beauty of West Virginia on this pristine 25-acre tract along Happy Hollow Road in Wood County. This property embodies everything that makes West Virginia special - hardwood forests, rolling topography, and abundant wildlife in a peaceful rural setting.\n\nThe 25-acre size is ideal for buyers seeking a manageable recreational property with serious hunting potential. The land\'s natural cover and terrain create excellent habitat for deer, turkey, and other game species. With good access via Happy Hollow Road, the property is easily accessible yet offers the seclusion that outdoor enthusiasts appreciate.\n\nThis tract is perfectly suited for a hunting camp, weekend retreat, or future home site where you can enjoy West Virginia\'s outdoors year-round. The property\'s location in Wood County provides a good balance of remoteness and accessibility to larger towns and amenities.\n\nWhether you\'re looking to establish a family hunting tradition, create a private getaway, or invest in West Virginia timberland, this 25-acre parcel offers excellent value and versatility. The property is ready for your vision - from simple recreational use to more developed improvements.',
    photos: [],
    roadFrontage: '',
    utilities: 'Electric, phone, rural water available',
    parcelId: '',
    youtubeUrl: '',
    mapEmbedHtml: '',
    createdAt: new Date('2023-12-05'),
  },
  {
    id: '4',
    slug: '26-acres-wood-county-wv',
    title: '26 Acres in Wood County, WV - Happy Hollow Road',
    state: 'WV',
    county: 'Wood',
    nearestTown: 'Parkersburg',
    acreage: 26,
    price: 132900,
    isNew: true,
    shortDescription: 'Quality 26-acre wooded tract on Happy Hollow Road in Wood County, WV. Excellent recreational land with mature timber, diverse wildlife habitat, and the seclusion of rural West Virginia hill country.',
    overview: 'This well-positioned 26-acre woodland tract on Happy Hollow Road represents an excellent opportunity to own quality recreational land in Wood County, West Virginia. The property features mature hardwood timber, natural terrain variations, and the peaceful rural character that defines this region.\n\nAt 26 acres, the property provides sufficient space for hunting, trail development, and establishing a private outdoor retreat. The land\'s natural features support healthy populations of whitetail deer and wild turkey, while the wooded cover and topography create ideal conditions for wildlife movement and bedding areas. Multiple potential building sites exist for those interested in constructing a cabin or full-time residence.\n\nLocated on Happy Hollow Road, the property offers practical access while maintaining the privacy and quiet that land buyers value. The surrounding area is characterized by similar rural holdings, ensuring your investment remains protected from unwanted development pressure.\n\nThis tract is ideal for hunters seeking their own private ground, families wanting a recreational property to enjoy for generations, or investors recognizing the enduring value of West Virginia timberland. With its combination of accessibility, natural features, and manageable size, this 26-acre parcel represents a solid land investment in the Mountain State.',
    photos: [],
    roadFrontage: '',
    utilities: 'Electric available',
    parcelId: '',
    youtubeUrl: '',
    mapEmbedHtml: '',
    createdAt: new Date('2024-01-25'),
  },
];
