import { Listing } from './types';

export const MOCK_LISTINGS: Listing[] = [
  {
    id: '1',
    slug: '45-acres-hocking-county-oh',
    title: '45 Acres - Hocking County Timber & Recreation Land',
    state: 'OH',
    county: 'Hocking',
    nearestTown: 'Logan',
    acreage: 45,
    price: 225000,
    isNew: true,
    shortDescription: 'Exceptional timber property with mature hardwoods, creek frontage, and abundant wildlife.',
    overview: 'This stunning 45-acre property in Hocking County offers the perfect blend of timber value and recreational opportunity. The land features mature hardwoods including oak, hickory, and maple, with a seasonal creek running through the northwest corner. Multiple building sites with excellent southern exposure. Wildlife including deer, turkey, and various game birds are abundant. Convenient access via maintained gravel road.',
    photos: ['/images/listings/listing-1-1.jpg', '/images/listings/listing-1-2.jpg', '/images/listings/listing-1-3.jpg', '/images/listings/listing-1-4.jpg'],
    roadFrontage: '450 feet on county road',
    utilities: 'Electric available at road',
    parcelId: 'HOC-2024-001',
    youtubeUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    mapEmbedHtml: '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d24429.237023216238!2d-82.40793!3d39.54016!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x88476c1e6b1f2b6d%3A0x1234!2sLogan%2C+OH!5e0!3m2!1sen!2sus!4v1234567890" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    slug: '120-acres-athens-county-oh',
    title: '120 Acres - Athens County Valley & Ridge Property',
    state: 'OH',
    county: 'Athens',
    nearestTown: 'Athens',
    acreage: 120,
    price: 480000,
    isNew: true,
    shortDescription: 'Diverse property with valley pasture, wooded ridges, pond, and mountain views.',
    overview: 'A rare opportunity to own 120 acres of diverse terrain in beautiful Athens County. This property features approximately 40 acres of open valley land suitable for pasture or crops, with the remaining 80 acres in mature mixed hardwoods climbing the ridges. A spring-fed pond of approximately 1 acre provides water for livestock and attracts waterfowl. Spectacular views from the ridge tops. Old barn foundation and multiple excellent building sites.',
    photos: ['/images/listings/listing-2-1.jpg', '/images/listings/listing-2-2.jpg', '/images/listings/listing-2-3.jpg'],
    roadFrontage: '800 feet',
    utilities: 'Electric and phone available',
    parcelId: 'ATH-2024-002',
    createdAt: new Date('2024-01-20'),
  },
  {
    id: '3',
    slug: '22-acres-wayne-county-wv',
    title: '22 Acres - Wayne County Hunting & Homestead Land',
    state: 'WV',
    county: 'Wayne',
    nearestTown: 'Wayne',
    acreage: 22,
    price: 88000,
    isNew: false,
    shortDescription: 'Secluded hunting land with excellent deer and turkey populations. Perfect for a cabin retreat.',
    overview: 'Well-positioned 22-acre tract ideal for hunting or a weekend cabin. The property is heavily wooded with a mix of hardwoods and some pine, providing excellent cover and food sources for wildlife. Evidence of significant deer and turkey activity throughout. A natural bench on the eastern side offers a level building site with privacy. Gated entrance with deeded access easement.',
    photos: ['/images/listings/listing-3-1.jpg', '/images/listings/listing-3-2.jpg', '/images/listings/listing-3-3.jpg', '/images/listings/listing-3-4.jpg', '/images/listings/listing-3-5.jpg'],
    roadFrontage: '200 feet',
    parcelId: 'WAY-2023-018',
    createdAt: new Date('2023-11-10'),
  },
  {
    id: '4',
    slug: '67-acres-ross-county-oh',
    title: '67 Acres - Ross County Farm & Timber',
    state: 'OH',
    county: 'Ross',
    nearestTown: 'Chillicothe',
    acreage: 67,
    price: 335000,
    isNew: false,
    shortDescription: 'Mixed-use property with tillable ground, woods, and income-producing timber.',
    overview: 'Productive 67-acre farm in Ross County featuring approximately 35 acres of tillable ground currently in row crops, with the balance in mature timber. The timber includes walnut, oak, and cherry with good merchantable value. Property has been well-maintained and offers multiple income streams. Rolling topography with good drainage.',
    photos: ['/images/listings/listing-4-1.jpg', '/images/listings/listing-4-2.jpg'],
    roadFrontage: '1,200 feet on paved road',
    utilities: 'Electric, phone, rural water available',
    parcelId: 'ROS-2023-024',
    createdAt: new Date('2023-12-05'),
  },
  {
    id: '5',
    slug: '185-acres-jackson-county-wv',
    title: '185 Acres - Jackson County Investment Property',
    state: 'WV',
    county: 'Jackson',
    nearestTown: 'Ripley',
    acreage: 185,
    price: 740000,
    isNew: true,
    shortDescription: 'Large tract with natural gas rights, timber value, and recreation potential.',
    overview: 'Outstanding 185-acre investment property offering multiple revenue opportunities. Property includes mineral rights and an existing natural gas lease providing annual income. Significant standing timber value with professional timber cruise available. Excellent hunting throughout with managed food plots already established. Internal trail system provides access to all corners of the property.',
    photos: ['/images/listings/listing-5-1.jpg', '/images/listings/listing-5-2.jpg', '/images/listings/listing-5-3.jpg', '/images/listings/listing-5-4.jpg', '/images/listings/listing-5-5.jpg', '/images/listings/listing-5-6.jpg'],
    roadFrontage: '2,400 feet',
    utilities: 'Electric available',
    parcelId: 'JAC-2024-003',
    youtubeUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    createdAt: new Date('2024-01-25'),
  },
  {
    id: '6',
    slug: '30-acres-vinton-county-oh',
    title: '30 Acres - Vinton County Recreational Retreat',
    state: 'OH',
    county: 'Vinton',
    nearestTown: 'McArthur',
    acreage: 30,
    price: 135000,
    isNew: false,
    shortDescription: 'Secluded wooded property near public hunting lands and ATV trails.',
    overview: 'Perfect recreational getaway on 30 acres of wooded hillside in Vinton County. Property borders public land, effectively expanding your hunting and recreation area. Situated near extensive ATV trail systems. Several potential camping or cabin sites with good southern exposure. Property has been selectively logged in the past, creating excellent edge habitat for wildlife.',
    photos: ['/images/listings/listing-6-1.jpg', '/images/listings/listing-6-2.jpg', '/images/listings/listing-6-3.jpg'],
    roadFrontage: '350 feet',
    parcelId: 'VIN-2023-031',
    createdAt: new Date('2023-10-20'),
  },
  {
    id: '7',
    slug: '52-acres-gallia-county-oh',
    title: '52 Acres - Gallia County River Bottom Farm',
    state: 'OH',
    county: 'Gallia',
    nearestTown: 'Gallipolis',
    acreage: 52,
    price: 260000,
    isNew: false,
    shortDescription: 'Prime river bottom ground with excellent soil and Ohio River views.',
    overview: 'Exceptional 52-acre farm featuring rich Ohio River bottom land. Approximately 45 acres are tillable with high-quality soil perfect for crops or pasture. Property includes nearly 1,000 feet of frontage along a scenic tributary of the Ohio River. Stunning views of the river valley from the higher ground. Property has been in row crops for decades with excellent yield history available.',
    photos: ['/images/listings/listing-7-1.jpg', '/images/listings/listing-7-2.jpg', '/images/listings/listing-7-3.jpg', '/images/listings/listing-7-4.jpg'],
    roadFrontage: '600 feet',
    utilities: 'Electric, phone, and municipal water available',
    parcelId: 'GAL-2023-027',
    createdAt: new Date('2023-11-18'),
  },
  {
    id: '8',
    slug: '14-acres-ritchie-county-wv',
    title: '14 Acres - Ritchie County Building Site',
    state: 'WV',
    county: 'Ritchie',
    nearestTown: 'Harrisville',
    acreage: 14,
    price: 56000,
    isNew: true,
    shortDescription: 'Affordable building site with mixed woods and open meadow.',
    overview: 'Nicely balanced 14-acre parcel with approximately 6 acres of open meadow and 8 acres of young timber. The open area provides an excellent building site with long-range views, while the wooded portion offers privacy and wildlife habitat. Property has been percolation tested with favorable results for conventional septic. Quiet country road with minimal traffic.',
    photos: ['/images/listings/listing-8-1.jpg', '/images/listings/listing-8-2.jpg'],
    roadFrontage: '400 feet',
    utilities: 'Electric available at road',
    parcelId: 'RIT-2024-005',
    createdAt: new Date('2024-02-01'),
  },
  {
    id: '9',
    slug: '95-acres-meigs-county-oh',
    title: '95 Acres - Meigs County Wildlife Sanctuary',
    state: 'OH',
    county: 'Meigs',
    nearestTown: 'Pomeroy',
    acreage: 95,
    price: 427500,
    isNew: false,
    shortDescription: 'Premier hunting property with managed wildlife habitat and food plots.',
    overview: 'Turn-key hunting property professionally managed for wildlife. Property features a network of established food plots totaling 8 acres, along with numerous fruit and mast-producing trees planted specifically for wildlife. Two established tree stand locations with elevated shooting houses. Internal road system provides easy access. Property is enrolled in conservation programs. Small cabin with sleeping quarters and basic amenities included.',
    photos: ['/images/listings/listing-9-1.jpg', '/images/listings/listing-9-2.jpg', '/images/listings/listing-9-3.jpg', '/images/listings/listing-9-4.jpg', '/images/listings/listing-9-5.jpg'],
    roadFrontage: '800 feet',
    utilities: 'Off-grid solar system at cabin',
    parcelId: 'MEI-2023-019',
    youtubeUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    createdAt: new Date('2023-09-15'),
  },
  {
    id: '10',
    slug: '38-acres-pike-county-oh',
    title: '38 Acres - Pike County Creek & Timber Property',
    state: 'OH',
    county: 'Pike',
    nearestTown: 'Piketon',
    acreage: 38,
    price: 171000,
    isNew: false,
    shortDescription: 'Beautiful property with year-round creek, waterfalls, and mature hardwoods.',
    overview: 'Stunning 38-acre property featuring a year-round creek with multiple small waterfalls and deep pools. The creek valley is surrounded by mature hardwood forest including oak, poplar, and hickory. Exceptional natural beauty makes this property ideal for a private estate or nature retreat. Wildlife is abundant. Property includes a maintained trail system that follows the creek and accesses the upper ridges.',
    photos: ['/images/listings/listing-10-1.jpg', '/images/listings/listing-10-2.jpg', '/images/listings/listing-10-3.jpg'],
    roadFrontage: '500 feet',
    utilities: 'Electric available',
    parcelId: 'PIK-2023-033',
    createdAt: new Date('2023-10-08'),
  },
  {
    id: '11',
    slug: '200-acres-washington-county-oh',
    title: '200 Acres - Washington County Legacy Property',
    state: 'OH',
    county: 'Washington',
    nearestTown: 'Marietta',
    acreage: 200,
    price: 1100000,
    isNew: true,
    shortDescription: 'Exceptional large tract with diverse terrain, lake, historic structures, and development potential.',
    overview: 'Rare opportunity to acquire a significant land holding in Washington County. This 200-acre property offers incredible diversity: approximately 50 acres of open pasture land, a 3-acre stocked lake, mature timber stands, and rolling wooded hills. Property includes a historic barn (circa 1890) and original farmhouse foundation. Multiple building sites with spectacular views. Property could be subdivided or maintained as a single estate. Fully fenced perimeter with three separate gated entrances.',
    photos: ['/images/listings/listing-11-1.jpg', '/images/listings/listing-11-2.jpg', '/images/listings/listing-11-3.jpg', '/images/listings/listing-11-4.jpg', '/images/listings/listing-11-5.jpg', '/images/listings/listing-11-6.jpg', '/images/listings/listing-11-7.jpg'],
    roadFrontage: '3,200 feet on two roads',
    utilities: 'Electric, phone, high-speed internet available',
    parcelId: 'WAS-2024-001',
    youtubeUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    mapEmbedHtml: '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d24429.237023216238!2d-81.44843!3d39.41538!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x88476c1e6b1f2b6d%3A0x5678!2sMarietta%2C+OH!5e0!3m2!1sen!2sus!4v1234567890" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>',
    createdAt: new Date('2024-02-10'),
  },
  {
    id: '12',
    slug: '76-acres-lawrence-county-oh',
    title: '76 Acres - Lawrence County Mixed-Use Farm',
    state: 'OH',
    county: 'Lawrence',
    nearestTown: 'Ironton',
    acreage: 76,
    price: 304000,
    isNew: false,
    shortDescription: 'Well-balanced farm with pasture, cropland, and timber. Suitable for livestock operation.',
    overview: 'Versatile 76-acre farm offering multiple agricultural opportunities. Property includes 30 acres of open land (combination of pasture and tillable ground), 40 acres of mixed timber, and 6 acres of managed food plots. Perimeter and cross-fencing in good condition. Two stock ponds. Property has supported a successful cattle operation for years. Good building sites with utilities available.',
    photos: ['/images/listings/listing-12-1.jpg', '/images/listings/listing-12-2.jpg', '/images/listings/listing-12-3.jpg', '/images/listings/listing-12-4.jpg'],
    roadFrontage: '900 feet',
    utilities: 'Electric, phone available',
    parcelId: 'LAW-2023-028',
    createdAt: new Date('2023-11-22'),
  },
];
